homeassistant:
  allowlist_external_dirs:
    - /config
http:
  server_host: 0.0.0.0
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12
    - 127.0.0.1
    - ::1
  trusted_hosts:
    - home-assistant-docker-c947.onrender.com
    - 0.0.0.0    
