homeassistant:
  name: Home Assistant
  unit_system: metric

http:
  server_host: 0.0.0.0
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 0.0.0.0/0
  trusted_hosts:
    - 0.0.0.0
    - localhost
    - home-assistant-docker-c947.onrender.com

logger:
  default: info
