homeassistant:
  name: Home Assistant
  unit_system: metric

http:
  server_host: 0.0.0.0
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  trusted_hosts:
    - home-assistant-docker-c947.onrender.com
    - localhost
    - 0.0.0.0
logger:
  default: warning
  logs:
    homeassistant.components.go2rtc.server: error
